"""empty message

Revision ID: 437f83261f2f
Revises: 5a3ce26f6b9c
Create Date: 2014-11-19 11:38:12.547715

"""

# revision identifiers, used by Alembic.
revision = '437f83261f2f'
down_revision = '5a3ce26f6b9c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
